### ISSUE TITLE
Skipping incompatible /usr/local/lib/libspotify.so error when installing

### ISSUE THREAD

**Issue by rajbala** [jodal/pyspotify#110]
I get this error when trying to install on Ubuntu 12.04 with Python 2.7.3  I have libspotify 12.1.51 installed.  I have python-dev installed as well.  Am I missing something by chance?

```
/usr/bin/ld: skipping incompatible /usr/local/lib/libspotify.so when searching for -lspotify
/usr/bin/ld: cannot find -lspotify
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

**Comment by emiliobasualdo** [comment]
hi @jodal , I´m having the same problem as @rajbala had. I have tested with the `file` command and got the same output as you. Do you have any idea why could this be happening?

**Comment by kingosticks** [comment]
On Ubuntu 12.04 also?

**Comment by emiliobasualdo** [comment]
16.04.3
