### ISSUE TITLE
Buffer underruns with PortAudioSink

### ISSUE THREAD

**Issue by funkzy** [jodal/pyspotify#132]
I modified `examples/play_track.py` to use PortAudio:

``` python
# Connect an audio sink
audio = spotify.PortAudioSink(session)
```

Every 10-20 seconds or so, I hear a blip in playback.

Details: 
- OS X 10.9.2
- Macbook Pro / 2.6 ghz processor
- portaudio: stable 19.20111121, HEAD (via Homebrew)
- PyAudio: 0.2.8 (released April 2014)
- Python: 2.7.5

**Comment by jodal** [comment]
Closing as libspotify and pyspotify are dead. See #215 for details.
