### ISSUE TITLE
pyspotify 2 on windows

### ISSUE THREAD

**Issue by tennox** [jodal/pyspotify#191]
This was already discussed heavily in #63 (for pyspotify 1) but then closed due to pyspotify 2 with the sentence:

> Feel free to open a new issue to discuss how to compile pyspotify 2 on Windows.

.

I'm still not able to install pyspotify on windows, here's for example the **pip installation** attempt:

> py -m pip install pyspotify
> Collecting pyspotify
>   Using cached pyspotify-2.0.5.tar.gz
> Requirement already satisfied (use --upgrade to upgrade): cffi>=1.0.0 in c:\python27\lib\site-packages (from pyspotify)
> Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\python27\lib\site-packages (from cffi>=1.0.0->pyspotify)
> Installing collected packages: pyspotify
>   Running setup.py install for pyspotify ... error
>     Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\manu\appdata\local\temp\pip-build-5e0iqe\pyspotify\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\manu\appdata\local\temp\pip-qlwt1f-record\install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win32-2.7
>     creating build\lib.win32-2.7\spotify
>     copying spotify\album.py -> build\lib.win32-2.7\spotify
>     copying spotify\artist.py -> build\lib.win32-2.7\spotify
>     copying spotify\audio.py -> build\lib.win32-2.7\spotify
>     copying spotify\config.py -> build\lib.win32-2.7\spotify
>     copying spotify\connection.py -> build\lib.win32-2.7\spotify
>     copying spotify\error.py -> build\lib.win32-2.7\spotify
>     copying spotify\eventloop.py -> build\lib.win32-2.7\spotify
>     copying spotify\image.py -> build\lib.win32-2.7\spotify
>     copying spotify\inbox.py -> build\lib.win32-2.7\spotify
>     copying spotify\link.py -> build\lib.win32-2.7\spotify
>     copying spotify\offline.py -> build\lib.win32-2.7\spotify
>     copying spotify\player.py -> build\lib.win32-2.7\spotify
>     copying spotify\playlist.py -> build\lib.win32-2.7\spotify
>     copying spotify\playlist_container.py -> build\lib.win32-2.7\spotify
>     copying spotify\playlist_track.py -> build\lib.win32-2.7\spotify
>     copying spotify\playlist_unseen_tracks.py -> build\lib.win32-2.7\spotify
>     copying spotify\search.py -> build\lib.win32-2.7\spotify
>     copying spotify\session.py -> build\lib.win32-2.7\spotify
>     copying spotify\sink.py -> build\lib.win32-2.7\spotify
>     copying spotify\social.py -> build\lib.win32-2.7\spotify
>     copying spotify\toplist.py -> build\lib.win32-2.7\spotify
>     copying spotify\track.py -> build\lib.win32-2.7\spotify
>     copying spotify\user.py -> build\lib.win32-2.7\spotify
>     copying spotify\utils.py -> build\lib.win32-2.7\spotify
>     copying spotify\version.py -> build\lib.win32-2.7\spotify
>     copying spotify_spotify_build.py -> build\lib.win32-2.7\spotify
>     copying spotify__init__.py -> build\lib.win32-2.7\spotify
>     running egg_info
>     writing requirements to pyspotify.egg-info\requires.txt
>     writing pyspotify.egg-info\PKG-INFO
>     writing top-level names to pyspotify.egg-info\top_level.txt
>     writing dependency_links to pyspotify.egg-info\dependency_links.txt
>     warning: manifest_maker: standard file '-c' not found
>     reading manifest file 'pyspotify.egg-info\SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     no previously-included directories found matching 'docs_build'
>     no previously-included directories found matching 'examples\tmp'
>     warning: no previously-included files matching '**pycache***' found anywhere in distribution
>     writing manifest file 'pyspotify.egg-info\SOURCES.txt'
>     copying spotify\api.h -> build\lib.win32-2.7\spotify
>     copying spotify\api.processed.h -> build\lib.win32-2.7\spotify
>     running build_ext
>     generating cffi module 'build\temp.win32-2.7\Release\spotify._spotify.c'
>     creating build\temp.win32-2.7
>     creating build\temp.win32-2.7\Release
>     building 'spotify._spotify' extension
>     creating build\temp.win32-2.7\Release\build
>     creating build\temp.win32-2.7\Release\build\temp.win32-2.7
>     creating build\temp.win32-2.7\Release\build\temp.win32-2.7\Release
>     C:\Users\Manu\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcbuild\temp.win32-2.7\Release\spotify._spotify.c /Fobuild\temp.win32-2.7\Release\build\temp.win32-2.7\Release\spotify._spotify.obj
>     spotify._spotify.c
>     build\temp.win32-2.7\Release\spotify._spotify.c(422) : fatal error C1083: Cannot open include file: 'libspotify/api.h': No such file or directory
>     error: command 'C:\Users\Manu\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2
>     ----------------------------------------
> Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\users\manu\appdata\local\temp\pip-build-5e0iqe\pyspotify\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\manu\appdata\local\temp\pip-qlwt1f-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\manu\appdata\local\temp\pip-build-5e0iqe\pyspotify\

**Comment by kingosticks** [comment]
From the [docs](https://pyspotify.mopidy.com/en/latest/installation/#install-from-source):
> However, since pyspotify is a Python wrapper around the libspotify library, pyspotify necessarily depends on libspotify and it must be installed first.

From your error message:
> fatal error C1083: Cannot open include file: 'libspotify/api.h': No such file or directory

Did you install libspotify somewhere that it can be found?

**Comment by zapu** [comment]
I had some success in compiling and using this library on Windows 7 (64bit but the libspotify.dll is 32bit I think).

Check my repo: https://github.com/zapu/pyspotify

libspotify on Windows expects the callbacks to be `__stdcall`, so I had to create new processed api.h and changed the `ffi.callbacks` a little bit.

It looks to work just fine, I tried the `cover.py` example. But getting this to actually play music will need some more work and integration with some audio library on Windows. I haven't looked into any of this yet.

P.S. Nice project, I really like it! Thanks for the hard work.

**Comment by adamcik** [comment]
Feel free to keep working on this, just be aware of the warning on https://developer.spotify.com/technologies/libspotify/

> Important! LibSpotify and CocoaLibSpotify are no longer under active development on any platform and are considered deprecated. If you are building applications for iOS or Android, please use the iOS SDK or Android SDK. We hope to be able to provide you with a new library for other platforms during 2016.
> 
> Until then, you can still provision new keys for your project. However, please be aware that we cannot offer active support or guarantee future functionality on LibSpotify or CocoaLibSpotify.

As for the said new library we've not heard anything yet. I would recommend to use the Web API for everything you can, and only rely on pyspotify where you have to.

**Comment by zapu** [comment]
Oh, sure, I know about that. I'm doing some music research project and I finally got fed up with talking to Spotify in C. Was lucky to find this library and that I was able to get it to work relatively quickly :)

**Comment by jodal** [comment]
Closing as libspotify and pyspotify are dead. See #215 for details.
