### ISSUE TITLE
Volume normalization

### ISSUE THREAD

**Issue by PhilippJust** [jodal/pyspotify#204]
Thank you for all the effort you put into mopidy and this project. :pray: 
I use pyspotify 2.1.3 through mopidy-spotify 4.0.1.
It seems to me that volume normalization is not working using pyspotify.
When there are songs from different albums in a playlist, the perceived loudness differs very significantly whereas it stays the same when playing the same songs in the spotify desktop app (version 1.1.46.916.g416cacf1 on Ubuntu 20.04).

Can anyone else confirm or refute my observation?

**Comment by jodal** [comment]
Closing as libspotify and pyspotify are dead. See #215 for details.
