### ISSUE TITLE
libspotify not available for arm64 architecture

### ISSUE THREAD

**Issue by ufoloko** [jodal/pyspotify#207]
Im trying to install pyspotify on Mac with M1 processor.

Im receiving an error

build/temp.macosx-11.2-arm64-2.7/spotify._spotify.c:569:10: fatal error: 'libspotify/api.h' file not found

Please help

**Comment by kingosticks** [comment]
There's no libspotify available for arm64. 

https://pyspotify.readthedocs.io/en/latest/installation/#libspotify

**Comment by jodal** [comment]
libspotify isn't available for your CPU architecture, arm64. As Spotify stopped maintenance of libspotify in 2015, I don't expect to see them release an arm64 build any time soon.

I haven't looked into possible solutions, but I imagine that it should be possible to run the 32-bit ARM builds somehow on a 64-bit ARM CPU using some emulation or similar? Long-term libspotify, and thus pyspotify, are dead projects.

**Comment by AndreKR** [comment]
I don't understand why this isn't solved by [Multiarch](https://wiki.debian.org/Multiarch/HOWTO). It works for [other 32-bit only software](https://thewayeye.net/posts/installing-raspotify-arm64/).

**Comment by jodal** [comment]
Closing as libspotify and pyspotify are dead. See #215 for details.
