### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [jodal/pyspotify#208]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine spotify/api.h and observe `reqeust`, however expect to see `request`.
- Examine spotify/api.h and observe `playlisys`, however expect to see `playlists`.
- Examine spotify/api.h and observe `overrided`, however expect to see `overridden`.
- Examine spotify/api.h and observe `otherwhise`, however expect to see `otherwise`.
- Examine spotify/api.h and observe `modifed`, however expect to see `modified`.
- Examine spotify/api.h and observe `inconsistant`, however expect to see `inconsistent`.
- Examine spotify/api.h and observe `expiery`, however expect to see `expiry`.
- Examine spotify/api.h and observe `decrese`, however expect to see `decrease`.
- Examine spotify/api.h and observe `abailable`, however expect to see `available`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/pyspotify/pull/new/bugfix_typos

Thanks.

**Comment by jodal** [comment]
`spotify/api.h` is lifted directly from the libspotify library. Thus, we're not interested in accepting any typo fixes to it.
