### ISSUE TITLE
Signal: 11 (SEGV)

### ISSUE THREAD

**Issue by ast261** [jodal/pyspotify#209]
See attachment.
[core.txt](https://github.com/jodal/pyspotify/files/6887534/core.txt)

**Comment by jodal** [comment]
What versions are you using?

What operating system address you on?

Is the segmentation fault reproducible?

If so, can you provide a script that can reproduce it?

**Comment by ast261** [comment]
> What versions are you using?

pyspotify: git master branch
the ripper: https://github.com/ast261/spotify-ripper

> What operating system are you on?

Manjaro (Python 3.9.6)

> Is the segmentation fault reproducible?

No, but it happens often and always in `sp_track_release`.
 
How can I build `_spotify.abi3.so` with debug code ?

`sp_track_release` has only one parameter (the track object). Maybe the dump occurs when the reference count of an invalid track is released ?

**Comment by ast261** [comment]
Any progress?
