### ISSUE TITLE
Sphinx v4.1.2 documentation fails 

### ISSUE THREAD

**Issue by sergiomb2** [jodal/pyspotify#211]
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.1.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 327, in eval_config_file
exec(code, namespace)
File "/builddir/build/BUILD/pyspotify-770aee08de274951b63e60bdd8835188b58e7862/docs/conf.py", line 67, in <module>
setattr(cls, method_name, method.__wrapped__)
TypeError: cannot set 'maketrans' attribute of immutable type 'str'

make: *** [Makefile:45: html] Error 2

**Comment by kingosticks** [comment]
That line 67 doesn't match our line 67 (https://github.com/jodal/pyspotify/blob/master/docs/conf.py#L67) what am I missing?

**Comment by kingosticks** [comment]
Yeh, I got there, thanks.

This is due to 3.10 change:
> [bpo-43682](https://bugs.python.org/issue43682): Static methods ([@staticmethod](https://docs.python.org/3/library/functions.html#staticmethod)) and class methods ([@classmethod](https://docs.python.org/3/library/functions.html#classmethod)) now inherit the method attributes (__module__, __name__, __qualname__, __doc__, __annotations__) and have a new __wrapped__ attribute. Patch by Victor Stinner.

Combined with a buggy implementation in our conf.py where we are not excluding built-ins

**Comment by sergiomb2** [comment]
thank you
